const DEFAULT_BANNER = [
  '// AUTO-GENERATED by @infernocms/next. Do not edit.',
  '// To regenerate, run `infernocms-next codegen` or rely on `withInfernoCMS()`.',
];

export interface EmitClientOptions {
  banner?: string[];
}

export function emitClient(opts: EmitClientOptions = {}): string {
  const banner = opts.banner ?? DEFAULT_BANNER;
  return [
    ...banner,
    '',
    `import { createReadClient, createWriteClientFactory } from '@infernocms/next/runtime';`,
    `import type { Schema, SlugCollection } from './types.js';`,
    '',
    'export const cms = createReadClient<Schema, SlugCollection>({',
    '  url: process.env.INFERNOCMS_URL,',
    '  readToken: process.env.INFERNOCMS_READ_TOKEN,',
    '});',
    '',
    'export const writeCms = createWriteClientFactory<Schema, SlugCollection>({',
    '  url: process.env.INFERNOCMS_URL,',
    '});',
    '',
  ].join('\n');
}
