import type { NormalizedConfig, NormalizedCollectionConfig, NormalizedFieldConfig } from 'infernocms';

const DEFAULT_BANNER = [
  '// AUTO-GENERATED by @infernocms/next. Do not edit.',
  '// To regenerate, run `infernocms-next codegen` or rely on `withInfernoCMS()`.',
];

export interface EmitTypesOptions {
  banner?: string[];
}

function toTypeName(collectionName: string): string {
  return collectionName.charAt(0).toUpperCase() + collectionName.slice(1);
}

function quoteKey(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : `'${name}'`;
}

function fieldType(field: NormalizedFieldConfig): string {
  switch (field.type) {
    case 'text':
    case 'textarea':
    case 'slug':
    case 'datetime':
    case 'date':
    case 'image':
    case 'file':
      return 'string';
    case 'select':
      return field.options && field.options.length > 0
        ? field.options.map((o) => `'${o}'`).join(' | ')
        : 'string';
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'json':
    case 'richtext':
      return 'unknown';
    case 'relation': {
      if (!field.collection) return 'unknown';
      const related = toTypeName(field.collection);
      return field.many ? `Array<number | ${related}>` : `number | ${related}`;
    }
    case 'blocks':
      return 'Array<{ type: string; id?: string; [key: string]: unknown }>';
    case 'link':
      return '{ url: string; label?: string; target?: string }';
    case 'group':
    case 'array': {
      if (!field.fields) return 'unknown';
      const nested = Object.entries(field.fields)
        .map(([n, f]) => {
          const opt = f.required ? '' : '?';
          return `${quoteKey(n)}${opt}: ${fieldType(f)}`;
        })
        .join('; ');
      const obj = `{ ${nested} }`;
      return field.type === 'array' ? `Array<${obj}>` : obj;
    }
    default:
      return 'unknown';
  }
}

function emitInterface(name: string, collection: NormalizedCollectionConfig): string {
  const lines: string[] = [`export interface ${toTypeName(name)} {`, '  id: number;'];
  for (const [fname, field] of Object.entries(collection.fields)) {
    const opt = field.required ? '' : '?';
    lines.push(`  ${quoteKey(fname)}${opt}: ${fieldType(field)};`);
  }
  if (collection.timestamps.createdAt.enabled) {
    const opt = collection.timestamps.createdAt.required ? '' : '?';
    lines.push(`  createdAt${opt}: string;`);
  }
  if (collection.timestamps.updatedAt.enabled) {
    const opt = collection.timestamps.updatedAt.required ? '' : '?';
    lines.push(`  updatedAt${opt}: string;`);
  }
  lines.push('}');
  return lines.join('\n');
}

export function emitTypes(config: NormalizedConfig, opts: EmitTypesOptions = {}): string {
  const banner = opts.banner ?? DEFAULT_BANNER;
  const interfaces = Object.entries(config.collections).map(([name, col]) =>
    emitInterface(name, col)
  );

  const schemaEntries = Object.keys(config.collections)
    .map((n) => `  ${quoteKey(n)}: ${toTypeName(n)};`)
    .join('\n');
  const schemaInterface = `export interface Schema {\n${schemaEntries}\n}`;

  const slugCollections = Object.entries(config.collections)
    .filter(([, c]) => Object.values(c.fields).some((f) => f.type === 'slug'))
    .map(([n]) => `'${n}'`);
  const slugType =
    slugCollections.length > 0
      ? `export type SlugCollection = ${slugCollections.join(' | ')};`
      : 'export type SlugCollection = never;';

  return [...banner, '', ...interfaces, '', schemaInterface, '', slugType, ''].join('\n');
}
